<!DOCTYPE html>
<html>
<head>
    <title>Melomaniac</title>
</head>

<body style="background-color: darkslategray;">

<h1 style="color:antiquewhite">Slut</h1>
<h4 style="color:antiquewhite">Lyrics Song by: Taylor Swift</h4>
<hr  style="color:antiquewhite">

<center>
<pre>
<h2>Taylor Swift</h2><h4>Singer/Composer/Actrist</h4>

<?php 
echo '<span style="color: antiquewhite;">Key of C</span>';
echo "\n";
echo '<span style="color: antiquewhite;">[Intro]</span>';
echo "\n";
echo "\n";
echo "\n";
echo '<span style="color: antiquewhite;">[Verse 1]</span>';
echo "\n";
echo '<span style="color: antiquewhite;">D</span>';
echo "\n";
echo '<span style="color: antiquewhite;"> Flamingo pink, Sunrise Boulevard</span>';
echo "\n";
echo '<span style="color: antiquewhite;">Bm            F#m          G</span>';
echo "\n";
echo '<span style="color: antiquewhite;">  Clink, clink, being this young is art</span>';
echo "\n";
echo '<span style="color: antiquewhite;">D</span>';
echo "\n";
echo '<span style="color: antiquewhite;"> Aquamarine, moonlit swimming pool</span>';
echo "\n";
echo '<span style="color: antiquewhite;">Bm       F#m      G</span>';
echo "\n";
echo '<span style="color: antiquewhite;">  What if   all I need is you?</span>';
echo "\n";
echo "\n";
echo "\n";
echo '<span style="color: antiquewhite;">[Pre-Chorus]</span>';
echo "\n";
echo '<span style="color: antiquewhite;">D</span>';
echo "\n";
echo '<span style="color: antiquewhite;">Got love-struck, went straight to my head</span>';
echo "\n";
echo "\n";
echo '<span style="color: antiquewhite;">Got lovesick all over my bed</span>';
echo "\n";
echo '<span style="color: antiquewhite;">Bm</span>';
echo "\n";
echo '<span style="color: antiquewhite;">Love to think you\'ll never forget</span>';
echo "\n";
echo '<span style="color: antiquewhite;">F#m                    G</span>';
echo "\n";
echo '<span style="color: antiquewhite;">   Handprints in wet cement</span>';
echo "\n";
echo '<span style="color: antiquewhite;">D</span>';
echo "\n";
echo '<span style="color: antiquewhite;"> Adorned with smoke on my clothes</span>';
echo "\n";
echo "\n";
echo '<span style="color: antiquewhite;">Lovelorn and nobody knows</span>';
echo "\n";
echo '<span style="color: antiquewhite;">Bm</span>';
echo "\n";
echo '<span style="color: antiquewhite;">  Love thorns all over this rose</span>';
echo "\n";
echo '<span style="color: antiquewhite;">F#m                        G</span>';
echo "\n";
echo '<span style="color: antiquewhite;">   I’ll pay the price, you won\'t</span>';
echo "\n";
echo "\n";
echo "\n";
echo "\n";
echo "\n";
echo '<span style="color: antiquewhite;">[Chorus]</span>';
echo "\n";
echo '<span style="color: antiquewhite;">    G</span>';
echo "\n";
echo '<span style="color: antiquewhite;">But if I\'m all dressed up</span>';
echo "\n";
echo "\n";
echo '<span style="color: antiquewhite;">They might as well be lookin’ at us</span>';
echo "\n";
echo '<span style="color: antiquewhite;">F#m</span>';
echo "\n";
echo '<span style="color: antiquewhite;">   And if they call me a slut</span>';
echo "\n";
echo '<span style="color: antiquewhite;">You know it might be worth it for once</span>';
echo "\n";
echo '<span style="color: antiquewhite;">Bm</span>';
echo "\n";
echo '<span style="color: antiquewhite;">  And if I\'m gonna be drunk</span>';
echo "\n";
echo '<span style="color: antiquewhite;">A/C#</span>';
echo "\n";
echo '<span style="color: antiquewhite;">    I might as well be drunk in love</span>';
echo "\n";
echo "\n";
echo "\n";
echo '<span style="color: antiquewhite;">[Verse 2]</span>';
echo "\n";
echo '<span style="color: antiquewhite;">D</span>';
echo "\n";
echo '<span style="color: antiquewhite;">Send the code, he\'s waitin\' there</span>';
echo "\n";
echo '<span style="color: antiquewhite;">    Bm                     F#m         G</span>';
echo "\n";
echo '<span style="color: antiquewhite;">The sticks and stones they throw froze mid-air</span>';
echo "\n";
echo '<span style="color: antiquewhite;">D</span>';
echo "\n";
echo '<span style="color: antiquewhite;">Everyone wants him, that was my crime</span>';
echo "\n";
echo '<span style="color: antiquewhite;">Bm</span>';
echo "\n";
echo '<span style="color: antiquewhite;">The wrong place at the right time</span>';
echo "\n";
echo '     <span style="color: antiquewhite;">Bm</span>';
echo "\n";
echo '<span style="color: antiquewhite;">And I break down, then he\'s pullin\' me in</span>';
echo "\n";
echo '     <span style="color: antiquewhite;">F#m                   N.C.</span>';
echo "\n";
echo '<span style="color: antiquewhite;">In a world of boys, he\'s a gentleman</span>';
echo "\n";
echo "\n";
echo "\n";
echo '<span style="color: antiquewhite;">[Pre-Chorus]</span>';
echo "\n";
echo '<span style="color: antiquewhite;">D</span>';
echo "\n";
echo '<span style="color: antiquewhite;">Got love-struck, went straight to my head (Straight to my head)</span>';
echo "\n";
echo "\n";
echo '<span style="color: antiquewhite;">Got lovesick all over my bed (Over my bed)</span>';
echo "\n";
echo '<span style="color: antiquewhite;">Bm</span>';
echo "\n";
echo '<span style="color: antiquewhite;">Love to think you\'ll never forget</span>';
echo "\n";
echo '<span style="color: antiquewhite;">F#m              G</span>';
echo "\n";
echo '<span style="color: antiquewhite;">   We’ll pay the price I guess</span>';
echo "\n";
echo '<span style="color: antiquewhite;">Key of C</span>';
echo "\n";
echo '<span style="color: antiquewhite;">[Intro]</span>';
echo "\n";
echo "\n";
echo "\n";
echo '<span style="color: antiquewhite;">[Verse 1]</span>';
echo "\n";
echo '<span style="color: antiquewhite;">D</span>';
echo "\n";
echo '<span style="color: antiquewhite;"> Flamingo pink, Sunrise Boulevard</span>';
echo "\n";
echo '<span style="color: antiquewhite;">Bm            F#m          G</span>';
echo "\n";
echo '<span style="color: antiquewhite;">  Clink, clink, being this young is art</span>';
echo "\n";
echo '<span style="color: antiquewhite;">D</span>';
echo "\n";
echo '<span style="color: antiquewhite;"> Aquamarine, moonlit swimming pool</span>';
echo "\n";
echo '<span style="color: antiquewhite;">Bm       F#m      G</span>';
echo "\n";
echo '<span style="color: antiquewhite;">  What if   all I need is you?</span>';
echo "\n";
echo "\n";
echo "\n";
echo '<span style="color: antiquewhite;">[Pre-Chorus]</span>';
echo "\n";
echo '<span style="color: antiquewhite;">D</span>';
echo "\n";
echo '<span style="color: antiquewhite;">Got love-struck, went straight to my head</span>';
echo "\n";
echo "\n";
echo '<span style="color: antiquewhite;">Got lovesick all over my bed</span>';
echo "\n";
echo '<span style="color: antiquewhite;">Bm</span>';
echo "\n";
echo '<span style="color: antiquewhite;">Love to think you\'ll never forget</span>';
echo "\n";
echo '<span style="color: antiquewhite;">F#m                    G</span>';
echo "\n";
echo '<span style="color: antiquewhite;">   Handprints in wet cement</span>';
echo "\n";
echo '<span style="color: antiquewhite;">D</span>';
echo "\n";
echo '<span style="color: antiquewhite;"> Adorned with smoke on my clothes</span>';
echo "\n";
echo "\n";
echo '<span style="color: antiquewhite;">Lovelorn and nobody knows</span>';
echo "\n";
echo '<span style="color: antiquewhite;">Bm</span>';
echo "\n";
echo '<span style="color: antiquewhite;">  Love thorns all over this rose</span>';
echo "\n";
echo '<span style="color: antiquewhite;">F#m                        G</span>';
echo "\n";
echo '<span style="color: antiquewhite;">   I’ll pay the price, you won\'t</span>';
echo "\n";
echo "\n";
echo "\n";
echo "\n";
echo "\n";
echo '<span style="color: antiquewhite;">[Chorus]</span>';
echo "\n";
echo '<span style="color: antiquewhite;">    G</span>';
echo "\n";
echo '<span style="color: antiquewhite;">But if I\'m all dressed up</span>';
echo "\n";
echo "\n";
echo '<span style="color: antiquewhite;">They might as well be lookin’ at us</span>';
echo "\n";
echo '<span style="color: antiquewhite;">F#m</span>';
echo "\n";
echo '<span style="color: antiquewhite;">   And if they call me a slut</span>';
echo "\n";
echo '<span style="color: antiquewhite;">You know it might be worth it for once</span>';
echo "\n";
echo '<span style="color: antiquewhite;">Bm</span>';
echo "\n";
echo '<span style="color: antiquewhite;">  And if I\'m gonna be drunk</span>';
echo "\n";
echo '<span style="color: antiquewhite;">A/C#</span>';
echo "\n";
echo '<span style="color: antiquewhite;">    I might as well be drunk in love</span>';
echo "\n";
echo "\n";
echo "\n";
echo '<span style="color: antiquewhite;">[Bridge]</span>';
echo "\n";
echo '<span style="color: antiquewhite;">D</span>';
echo "\n";
echo '<span style="color: antiquewhite;">Half asleep, takin\' your time</span>';
echo "\n";
echo '<span style="color: antiquewhite;">                                      Bm</span>';
echo "\n";
echo '<span style="color: antiquewhite;">In the tangerine, neon light, this is luxury</span>';
echo "\n";
echo '<span style="color: antiquewhite;">                            F#m</span>';
echo "\n";
echo '<span style="color: antiquewhite;">You’re not sayin\' you\'re in love with me</span>';
echo "\n";
echo '<span style="color: antiquewhite;">G</span>';
echo "\n";
echo '<span style="color: antiquewhite;">But you\'re going to</span>';
echo "\n";
echo '<span style="color: antiquewhite;">D</span>';
echo "\n";
echo '<span style="color: antiquewhite;">Half awake, takin\' your chances</span>';
echo "\n";
echo '<span style="color: antiquewhite;"> </span>';
echo "\n";
echo '<span style="color: antiquewhite;">It\'s a big mistake, I said, "It might blow up in your</span>';
echo "\n";
echo '<span style="color: antiquewhite;">Bm                                   F#m</span>';
echo "\n";
echo '<span style="color: antiquewhite;">Pretty face", I\'m not saying, "Do it anyway" (Do it anyway)</span>';
echo "\n";
echo '<span style="color: antiquewhite;">G</span>';
echo "\n";
echo '<span style="color: antiquewhite;">But you\'re going to</span>';
echo "\n";
echo "\n";
echo "\n";
echo "\n";
echo '<span style="color: antiquewhite;">[Outro]</span>';
echo "\n";
echo '<span style="color: antiquewhite;">G</span>';
echo "\n";
echo '<span style="color: antiquewhite;"> Up!</span>';
echo "\n";
echo '<span style="color: antiquewhite;">F#m</span>';
echo "\n";
echo '<span style="color: antiquewhite;">   And if they call me a slut!</span>';
echo "\n";
echo '<span style="color: antiquewhite;">You know it might be worth it for once</span>';
echo "\n";
echo '<span style="color: antiquewhite;">Bm</span>';
echo "\n";
echo '<span style="color: antiquewhite;">  And if I\'m gonna be drunk!</span>';
echo "\n";
echo '<span style="color: antiquewhite;">A/C#                            N.C.</span>';
echo "\n";
echo '<span style="color: antiquewhite;">    I might as well be drunk in love</span>';

?>
</center>


</pre>
<hr>
<a href="Index.php" style="text-decoration: none; color:antiquewhite;" ><h2> BACK </h2></a>

</body>
</html>