<!DOCTYPE html>
<html>
<head>
    <title>Melomaniac</title>
</head>

<body style="background-color: darkslategray;">



<h1 style="color:antiquewhite"> Lemon Tree </h1>
<h4 style="color:antiquewhite">Lyrics Song by: Fools Garden</h4>


<center>
<hr  style="color:antiquewhite">
<pre>
<h2>Fools Garden</h2><h4>Band</h4>


<?php 
echo '<span style="color: antiquewhite;"">Key of G</span>';
echo "\n";

echo"\n";

echo '<span style="color: antiquewhite;">[Em]Im Sitting Here [Bm]In A Boring Room </span>';
echo "\n";
echo '<span style="color: antiquewhite;"">[Em]Its Just Another Rainy Sunday [Bm]Afternoon</span>';
echo "\n";
echo '<span style="color: antiquewhite;">[Em]Im Wasting My Time I Got [Bm]Nothing To Do </span>';
echo "\n";
echo '<span style="color: antiquewhite;"">[Em]Im Hanging Around Im [Bm]Waiting For You</span>';
echo "\n";
echo '<span style="color: antiquewhite;">But [Am]Nothing Ever Happens - [Bm]And I [Em]Wonder</span>';
echo "\n";
echo "\n
";
echo "\n";
echo '<span style="color: antiquewhite;"">[Em]Im Driving Around [Bm]In My Car </span>';
echo "\n";
echo '<span style="color: antiquewhite;">[Em]Im Driving Too Fast Im Driving [Bm]Too Far</span>';
echo "\n";
echo '<span style="color: antiquewhite;"">[Em]Id Like To Change My Point [Bm]Of View </span>';
echo "\n";
echo '<span style="color: antiquewhite;">[Em]I Feel So Lonely Im Waiting [Bm]For You</span>';
echo "\n";
echo '<span style="color: antiquewhite;"">But [Am]Nothing Ever Happens - [Bm]And I [Em]Wonder</span>';
echo "\n";

echo "\n";
echo "\n";
echo '<span style="color: antiquewhite;">[G]I Wonder How I [D]Wonder Why</span>';
echo "\n";
echo '<span style="color: antiquewhite;"">[Em]Yesterday You Told Me bout The [Bm]Blue Blue Sky</span>';
echo "\n";
echo '<span style="color: antiquewhite;">[C]And All That I Can [D]See Is Just A Yellow [G]Lemon-tree [D] </span>';
echo "\n";
echo '<span style="color: antiquewhite;"">[G]Im Turning My Head [D]Up And Down </span>';
echo "\n";
echo '<span style="color: antiquewhite;">[Em]Im Turning Turning Turning Turning [Bm]Turning Around </span>';
echo "\n";
echo '<span style="color: antiquewhite;"">[C]And All That I Can [A]See Is Just A Yellow [D]Lemon-tree</span>';
echo "\n";

echo "\n";
echo "\n";
echo '<span style="color: antiquewhite;">[Em] [Bm] [Em] [Bm] [Am] [Bm] [Em] 
dadada....</span>';
echo "\n";
echo "\n";
echo "\n";
echo '<span style="color: antiquewhite;"">[Em]Im Sitting Here [Bm]I Miss The Power </span>';
echo "\n";
echo '<span style="color: antiquewhite;">[Em]Id Like To Go Out Taking A [Bm]Shower </span>';
echo "\n";
echo '<span style="color: antiquewhite;"">[Em]But Theres A Heavy Cloud [Bm]Inside My Head</span>';
echo "\n";
echo '<span style="color: antiquewhite;">[Em]I Feel So Tired Put Myself [Bm]Into Bed </span>';
echo "\n";
echo '<span style="color: antiquewhite;"">[Am]Where Nothing Ever [Bm]Happens - And [Em]I Wonder</span>';
echo "\n";

echo "\n";
echo "\n";
echo '<span style="color: antiquewhite;">[B]Isolation - [Em]Is Not Good For Me </span>';
echo "\n";
echo '<span style="color: antiquewhite;">[D]Isolation - [G]I Dont Want To [B]Sit On A Lemon-tree </span>';
echo "\n";

?>
</center>

</pre>

<hr>
<a href="Index.php" style="text-decoration: none; color:antiquewhite;" ><h2> BACK</h2></a>

</body>
</html>